# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    args: ['--markdown-linebreak-ext=md',]
  - id: end-of-file-fixer
  - id: check-added-large-files
- repo: https://github.com/PyCQA/autoflake
  rev: v2.0.2
  hooks:
  - id: autoflake
    language_version: python3
    args: [
      '--in-place',
      '--expand-star-imports',
      '--remove-all-unused-imports',
      '--remove-unused-variables',
      '--remove-duplicate-keys',
    ]
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    language_version: python3
    args: ['--profile', 'black', '--line-length', '120',]
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    language_version: python3
    args: ['--preview', '--line-length', '120', '--target-version', 'py310',]
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.4.0
  hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
